# Solving Systems of Linear Equations with NumPy - Lab

## Introduction 

Now we have gathered all the required skills needed to solve systems of linear equations. We saw why need to calculate inverses of matrices, followed by matrix multiplication to figure the values of unknown variables. 

Following exercises present some problems that can be converted into a system of linear equations. Solve the problems for the values of unknown variables. 

## Objectives
You will be able to:

* Build a system of equations from given problem by creating matrix and vectors in NumPy
* Calculate the inverse and dot-product to get the values for unknown variables.
* Solve linear equations using `numpy.linalg.solve()`

In [1]:
import numpy as np

## Exercise 1

A coffee shop is having a sale on coffee and tea. 

On day 1, 29 bags of coffee and 41 bags of tea was sold, giving a total of 490 dollars.

On day 2, they sold 23 bags of coffee and 41 bags of tea, for which customers paid a total of 448 dollars.  

How much does each bag cost?

In [20]:
# Solution:
A = np.array([[29,41],[23,41]])
B = np.array([[490,448]]).T

C = np.linalg.inv(A).dot(B)
C

D = np.linalg.solve(A,B)
D

array([[7.],
       [7.]])

In [13]:
# Explain your answer in terms of prices
Both cost 7 dollars per bag.

## Exercise 2:

The cost of admission to a popular music concert was 162 dollars for 12 children and 3 adults. 

The admission was 122 dollars for 8 children and 3 adults in another music concert. 

How much was the admission for each child and adult?

In [21]:
# Create a system of equations
A = np.array([[12,3],[8,3]])
B = np.array([[162,122]]).T

np.linalg.solve(A,B)


array([[10.],
       [14.]])

##### Describe your result
A child ticket costs 10 dollars and an adult ticket costs 14 dollars

## Exercise 3:

You want to make a certain kind of tropical punch, using bananas, oranges, and papayas. 

Suppose you don't know how many of each to put in the punch, but you know that there are seven pieces of fruit in the mix, and there are twice as many oranges as bananas. 

You also know that the seven pieces of fruit cost \$5.25, 

where bananas cost \$.50 each, oranges cost \$.75 each, and papayas cost \$1.25 each.

How many bananas, oranges and papayas would you need to make this punch ?

In [23]:
# Create a system of equations
A = np.array([[1,1,1],[.5,.75,1.25], [2,-1,0]])
B = np.array([[7,5.25,0]]).T

np.linalg.solve(A,B)


array([[2.],
       [4.],
       [1.]])

In [ ]:
# Explain your answer
"""You would need 2 banannas, 4 oranges, and 1 papaya."""

## Exercise 4

A landlord owns 3 houses, a 1-bedroom, a 2-bedroom , and a 3-bedroom house. 

The total rent he receives is 1240 dollars. 

He needs to make some repairs, where it costs 10% of the 1-bedroom house’s rent for its repairs, 20% of the 2-bedroom for its repairs, and 30% of the 3-bedroom house's rent for its repairs.  The total repair bill for all three houses was $276. 

The 3-bedroom house's rent is twice the 1-bedroom house’s rent. 

How much is the individual rent for three houses?

In [25]:
# Create a system of equations
A = np.array([[1,1,1], [.1,.2,.3], [2,0,-1]])
B = np.array([[1240,276,0]]).T

np.linalg.solve(A,B)

array([[280.],
       [400.],
       [560.]])

In [26]:
# Explain your answer
'''The price of the one bedroom is 280, two bedroom is 400, and 3 bedroom is 560.'''

'The price of the one bedroom is 280, two bedroom is 400, and 3 bedroom is 560.'

## Summary
In this lab, we saw how to use Numpy to solve linear equations by taking inverses and matrix multiplication and also using numpy's `.solve()`. We shall now take these skills forward and see how we can define a simple regression problem using linear algebra and solve it with numpy, only using the skills that we have learnt so far. 